// CONSTANT VALUES
// You can add more values here, based on your needs,

export const TYPES = {
    HIDE_ALL_ALLOTMENT_PANE: 'HIDE_ALL_ALLOTMENT_PANE',
    SHOW_ALL_ALLOTMENT_PANE: 'SHOW_ALL_ALLOTMENT_PANE',

    SET_DEFAULT_THEME_TO_DAY: 'SET_DEFAULT_THEME_TO_DAY',
    SET_DEFAULT_THEME_TO_NIGHT: 'SET_DEFAULT_THEME_TO_NIGHT',

    SET_DASHBOARD_PAGE_HAS_RENDERED: 'SET_DASHBOARD_PAGE_HAS_RENDERED',
    SET_HAS_CACHED_REPO_ID_RETRIEVED_ONCE: 'SET_HAS_CACHED_REPO_ID_RETRIEVED_ONCE',
    SET_DASHBOARD_HAS_ALLOWED_TO_RERENDERED: 'SET_DASHBOARD_HAS_ALLOWED_TO_RERENDERED',

    CURRENT_USER_FETCHING_INIT: 'CURRENT_USER_FETCHING_INIT',
    CURRENT_USER_FETCHED_FAILD: 'CURRENT_USER_FETCHED_FAILD',
    CURRENT_USER_FETCHED_SUCCESS: 'CURRENT_USER_FETCHED_SUCCESS',

    USER_FETCHING_BY_ID_INIT: 'USER_FETCHING_BY_ID_INIT',
    USER_FETCHED_BY_ID_FAILD: 'USER_FETCHED_BY_ID_FAILD',
    USER_FETCHED_BY_ID_SUCCESS: 'USER_FETCHED_BY_ID_SUCCESS',

    APP_IS_ONLINE: 'APP_IS_ONLINE',
    APP_IS_OFFLINE: 'APP_IS_OFFLINE',

    SETTINGS_UPDATE: 'SETTINGS_UPDATE',
    SETTINGS_INITIAL_LOAD: 'SETTINGS_INITIAL_LOAD',

    AUTH_ON_ERROR: 'AUTH_ON_ERROR',
    AUTH_ON_INIT: 'AUTH_ON_INIT',
    AUTH_ON_SUCCESS: 'AUTH_ON_SUCCESS',

    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',

    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',

    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',

    GIVE_STATUS_PERMISSION: 'GIVE_STATUS_PERMISSION',
    REMOVE_STATUS_PERMISSION: 'REMOVE_STATUS_PERMISSION',

    GIVE_LOGOUT_PERMISSION: 'GIVE_LOGOUT_PERMISSION',
    REMOVE_LOGOUT_PERMISSION: 'REMOVE_LOGOUT_PERMISSION',

    GIVE_SETTINGS_PERMISSION: 'GIVE_SETTINGS_PERMISSION',
    REMOVE_SETTINGS_PERMISSION: 'REMOVE_SETTINGS_PERMISSION',

    RESET_OPTION_PERMISSIONS_TO_DEFAULT: 'RESET_OPTION_PERMISSIONS_TO_DEFAULT',

    SHOW_NETWORK_ISSUE_PANEL: 'SHOW_NETWORK_ISSUE_PANEL',
    HIDE_NETWORK_ISSUE_PANEL: 'HIDE_NETWORK_ISSUE_PANEL',

    SHOW_LOADING_PANEL: 'SHOW_LOADING_PANEL',
    HIDE_LOADING_PANEL: 'HIDE_LOADING_PANEL',

    CREATE_NEW_REDIRECT_REQUEST: 'CREATE_NEW_REDIRECT_REQUEST',
    CONSUME_REDIRECT_REQUEST_SUCCESSFULLY: 'CONSUME_REDIRECT_REQUEST_SUCCESSFULLY',

    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    LOAD_INITIAL_SETTINGS_FROM_CACHED: 'LOAD_INITIAL_SETTINGS_FROM_CACHED',

    UPDATE_SETTINGS_SHOW_NOTIFICATIONS: 'UPDATE_SETTINGS_SHOW_NOTIFICATIONS',
    UPDATE_SETTINGS_TOGGLE_SHOW_NOTIFICATIONS: 'UPDATE_SETTINGS_TOGGLE_SHOW_NOTIFICATIONS',

    UPDATE_SETTINGS_DARK_THEME: 'UPDATE_SETTINGS_DARK_THEME',
    UPDATE_SETTINGS_PLAY_SOUND: 'UPDATE_SETTINGS_PLAY_SOUND',

    UPDATE_SETTINGS_IMAGE_PADDING: 'UPDATE_SETTINGS_IMAGE_PADDING',

    SAVE_USER_DOCUMENT: 'SAVE_USER_DOCUMENT',
    UPDATE_USER_DOCUMENT: 'UPDATE_USER_DOCUMENT',
    SAVE_USER_NOTIFICATIONS: 'SAVE_USER_NOTIFICATIONS',

    RESET_ALL_STATES: 'RESET_ALL_STATES',

    SAVE_ALL_PAYMENTS_HISTORY: 'SAVE_ALL_PAYMENTS_HISTORY',

    SAVE_COOKIE_DETAILS: 'SAVE_COOKIE_DETAILS',
    UPDATE_COOKIE_DETAILS: 'UPDATE_COOKIE_DETAILS',
}